import expeditionImage1 from "@assets/stock_images/mountain_expedition__228548ef.jpg";
import expeditionImage2 from "@assets/stock_images/mountain_expedition__b33a227e.jpg";
import expeditionImage3 from "@assets/stock_images/mountain_expedition__494acab3.jpg";
import heroImage1 from "@assets/stock_images/majestic_mountain_pe_743f6593.jpg";
import heroImage2 from "@assets/stock_images/majestic_mountain_pe_34e27685.jpg";
import nangaParbatImage1 from "@assets/nanga_parbat_1_1766090260999.png";
import nangaParbatImage2 from "@assets/nanga_perbat_2_1766090261000.png";

export interface ExpeditionTimeline {
  day: string;
  title: string;
  description: string;
}

export interface ExpeditionData {
  id: string;
  slug: string;
  name: string;
  altitude: string;
  location: string;
  duration: string;
  difficulty: string;
  bestSeason: string;
  price: number;
  groupSize: string;
  image: string;
  gallery?: string[];
  description: string;
  overview: string;
  timeline: ExpeditionTimeline[];
  servicesIncluded: string[];
  servicesNotIncluded: string[];
  requirements: string[];
  highlights: string[];
}

export const expeditions: ExpeditionData[] = [
  {
    id: "k2",
    slug: "k2-expedition",
    name: "K2 Expedition",
    altitude: "8,611m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "60-65 Days",
    difficulty: "Extremely Difficult",
    bestSeason: "June - August",
    price: 45000,
    groupSize: "6-12 climbers",
    image: expeditionImage1,
    description: "K2, the second highest mountain in the world, stands at 8,611 meters. Known as the 'Savage Mountain,' K2 is considered the most difficult and dangerous climb of all the 8,000m peaks.",
    overview: "The K2 Expedition is the ultimate mountaineering challenge. Located in the Karakoram Range on the China-Pakistan border, K2 demands exceptional climbing skills, physical fitness, and mental fortitude. Our expedition provides comprehensive support including experienced high-altitude guides, premium equipment, and thorough acclimatization schedules to maximize your summit success.",
    timeline: [
      { day: "Day 1-2", title: "Arrival in Islamabad", description: "Arrive in Islamabad. Team briefing, gear check, and documentation. Rest and acclimatization." },
      { day: "Day 3", title: "Fly to Skardu", description: "Scenic flight to Skardu (weather permitting) or drive via Karakoram Highway. Check into hotel." },
      { day: "Day 4-5", title: "Skardu Acclimatization", description: "Rest days in Skardu. Visit local attractions, final gear purchases, and team preparation." },
      { day: "Day 6-7", title: "Drive to Askole", description: "Jeep drive from Skardu to Askole, the last village before the trek begins. Organize porters and supplies." },
      { day: "Day 8-14", title: "Trek to Base Camp", description: "7-day trek through the Baltoro Glacier to K2 Base Camp (5,150m). Stops at Jola, Paiju, Urdukas, Gore II, and Concordia." },
      { day: "Day 15-20", title: "Base Camp Setup", description: "Establish base camp, acclimatization walks, and preparation for climbing. Medical checks and team meetings." },
      { day: "Day 21-35", title: "Rotations to Higher Camps", description: "Progressive acclimatization climbs. Establish Camp 1 (6,100m), Camp 2 (6,700m), and Camp 3 (7,300m)." },
      { day: "Day 36-50", title: "Summit Push Window", description: "Wait for optimal weather window. Final rest at base camp before summit attempt via Camp 4 (7,800m) to summit." },
      { day: "Day 51-57", title: "Descent & Trek Out", description: "Descend from summit, pack up camps, and trek back to Askole through Concordia and Baltoro." },
      { day: "Day 58-60", title: "Return Journey", description: "Drive to Skardu, fly to Islamabad. Celebration dinner and expedition debrief." },
    ],
    servicesIncluded: [
      "All government permits and royalties",
      "Liaison Officer and their expenses",
      "Experienced high-altitude climbing guides",
      "All meals at base camp and higher camps",
      "High-altitude tents and camping equipment",
      "Fixed ropes and technical climbing gear",
      "Oxygen bottles and regulators for summit",
      "Satellite phone and communication equipment",
      "Emergency evacuation insurance",
      "Porter and pack animal services for approach",
      "Airport transfers and ground transportation",
      "Hotel accommodation in cities",
    ],
    servicesNotIncluded: [
      "International flights to/from Pakistan",
      "Personal climbing gear and clothing",
      "Personal travel and medical insurance",
      "Tips and gratuities for staff",
      "Extra oxygen bottles beyond allocation",
      "Personal expenses and souvenirs",
      "Visa fees and passport expenses",
      "Additional hotel nights due to delays",
    ],
    requirements: [
      "Previous 8000m peak experience strongly recommended",
      "Minimum 7000m summit experience required",
      "Technical ice and rock climbing proficiency",
      "Excellent physical conditioning",
      "Medical clearance for high altitude",
      "Current mountaineering insurance",
    ],
    highlights: [
      "Summit the world's second highest peak",
      "Experience the legendary Baltoro Glacier",
      "Camp at the iconic Concordia with views of four 8000m peaks",
      "Challenge yourself on the most technical 8000m mountain",
    ],
  },
  {
    id: "nanga-parbat",
    slug: "nanga-parbat-expedition",
    name: "Nanga Parbat Expedition",
    altitude: "8,126m",
    location: "Diamer District, Pakistan",
    duration: "45-50 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - August",
    price: 35000,
    groupSize: "6-10 climbers",
    image: nangaParbatImage1,
    gallery: [nangaParbatImage1, nangaParbatImage2, nangaParbatImage1],
    description: "Nanga Parbat, the 'Killer Mountain,' rises 8,126 meters in the western Himalayas. It features the world's largest mountain face - the Rupal Face - rising 4,600m from base to summit.",
    overview: "The Nanga Parbat Expedition offers a challenging climb on one of the world's most dramatic peaks. Known for its massive size and unpredictable weather, Nanga Parbat requires excellent mountaineering skills. We offer routes via the Diamir Face (normal route) or the more challenging Rupal Face for experienced climbers.",
    timeline: [
      { day: "Day 1-2", title: "Arrival in Islamabad", description: "Arrive in Islamabad. Team briefing, permits verification, and gear check. Hotel accommodation." },
      { day: "Day 3", title: "Drive to Chilas", description: "Drive along the Karakoram Highway to Chilas. Views of the Indus River and Himalayan foothills." },
      { day: "Day 4", title: "Drive to Herligkoffer Base", description: "Continue drive to Diamir valley. Short trek to Herligkoffer Base Camp area." },
      { day: "Day 5-8", title: "Trek to Base Camp", description: "4-day trek to Diamir Base Camp (4,100m). Gradual acclimatization along the route." },
      { day: "Day 9-14", title: "Base Camp Acclimatization", description: "Establish base camp, acclimatization hikes, and preparation for climbing phase." },
      { day: "Day 15-30", title: "Rotations to Higher Camps", description: "Establish Camp 1 (5,000m), Camp 2 (5,800m), and Camp 3 (6,700m). Multiple acclimatization rotations." },
      { day: "Day 31-40", title: "Summit Push Window", description: "Wait for weather window. Summit push via Camp 4 (7,200m) to the summit (8,126m)." },
      { day: "Day 41-45", title: "Descent & Return", description: "Descend, pack up camps, trek out to road head. Drive back to Islamabad." },
    ],
    servicesIncluded: [
      "Climbing and trekking permits",
      "Liaison Officer expenses",
      "Professional mountain guides",
      "All meals at base camp and above",
      "High-altitude camping equipment",
      "Fixed ropes and anchors",
      "Supplemental oxygen for summit",
      "Emergency communication devices",
      "Helicopter rescue insurance",
      "Porter services to base camp",
      "Ground transportation in Pakistan",
      "City hotel accommodations",
    ],
    servicesNotIncluded: [
      "International airfare",
      "Personal climbing equipment",
      "Travel and medical insurance",
      "Staff gratuities",
      "Extra oxygen beyond standard",
      "Personal expenses",
      "Visa costs",
      "Delays due to weather",
    ],
    requirements: [
      "Previous 7000m+ peak experience",
      "Strong technical climbing skills",
      "Excellent physical fitness",
      "High altitude medical clearance",
      "Comprehensive mountaineering insurance",
    ],
    highlights: [
      "Climb the 'Killer Mountain' - 9th highest peak",
      "Witness the massive Rupal Face",
      "Experience authentic Himalayan adventure",
      "Stunning views of the western Himalayas",
    ],
  },
  {
    id: "gasherbrum",
    slug: "gasherbrum-expedition",
    name: "Gasherbrum I & II Expedition",
    altitude: "8,080m / 8,035m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "55-60 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - August",
    price: 38000,
    groupSize: "6-10 climbers",
    image: expeditionImage3,
    description: "The Gasherbrum peaks offer an incredible double-header expedition. Gasherbrum I (Hidden Peak) at 8,080m and Gasherbrum II at 8,035m are the 11th and 13th highest mountains in the world.",
    overview: "Our Gasherbrum Expedition offers the unique opportunity to summit two 8000m peaks in one expedition. Located in the Karakoram Range, these peaks share a similar approach via the Baltoro Glacier. Gasherbrum II is often climbed first as preparation for the more technical Gasherbrum I.",
    timeline: [
      { day: "Day 1-2", title: "Arrival in Islamabad", description: "Arrive in Islamabad. Expedition briefing, permit verification, and equipment check." },
      { day: "Day 3", title: "Fly to Skardu", description: "Morning flight to Skardu with spectacular mountain views. Hotel check-in and rest." },
      { day: "Day 4-5", title: "Skardu Preparation", description: "Organize porters, final supplies, and team preparation. Acclimatization walks." },
      { day: "Day 6-7", title: "Drive to Askole", description: "Scenic jeep drive to Askole village. Porter and equipment organization." },
      { day: "Day 8-14", title: "Trek to Base Camp", description: "7-day trek through Baltoro Glacier via Concordia to Gasherbrum Base Camp (5,200m)." },
      { day: "Day 15-20", title: "Base Camp Setup", description: "Establish base camp, acclimatization, and preparation for climbing both peaks." },
      { day: "Day 21-35", title: "GII Climb & Rotations", description: "Establish camps on Gasherbrum II. Summit GII (8,035m) as acclimatization for GI." },
      { day: "Day 36-48", title: "GI Summit Push", description: "After GII success, attempt Gasherbrum I (Hidden Peak) at 8,080m." },
      { day: "Day 49-55", title: "Descent & Trek Out", description: "Pack up camps, trek back to Askole via Concordia and Baltoro." },
      { day: "Day 56-60", title: "Return to Islamabad", description: "Drive and fly to Islamabad. Expedition debrief and celebration." },
    ],
    servicesIncluded: [
      "Permits for both Gasherbrum I & II",
      "Liaison Officer support",
      "IFMGA certified guides",
      "All base camp and high camp meals",
      "High-altitude tents and equipment",
      "Fixed ropes and technical gear",
      "Supplemental oxygen supplies",
      "Satellite communication",
      "Emergency evacuation coverage",
      "Porter services throughout",
      "All ground transportation",
      "Hotel stays in cities",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal climbing gear",
      "Personal insurance policies",
      "Tips for local staff",
      "Additional oxygen requests",
      "Personal spending money",
      "Pakistan visa fees",
      "Weather delay costs",
    ],
    requirements: [
      "Previous 6000m+ climbing experience",
      "Technical ice climbing ability",
      "Excellent cardiovascular fitness",
      "High altitude medical approval",
      "Valid mountaineering insurance",
    ],
    highlights: [
      "Climb two 8000m peaks in one expedition",
      "Trek the legendary Baltoro Glacier",
      "Experience the beauty of Concordia",
      "Achieve rare double 8000m summit",
    ],
  },
  {
    id: "broad-peak",
    slug: "broad-peak-expedition",
    name: "Broad Peak Expedition",
    altitude: "8,051m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "50-55 Days",
    difficulty: "Difficult",
    bestSeason: "June - August",
    price: 32000,
    groupSize: "6-12 climbers",
    image: heroImage1,
    description: "Broad Peak, at 8,051m, is the 12th highest mountain in the world. Known for its massive summit plateau, it offers a technically accessible route compared to its neighbor K2.",
    overview: "The Broad Peak Expedition is an excellent choice for climbers seeking their first 8000m summit. While still demanding extreme fitness and mountaineering skills, the normal route is less technical than K2 or Nanga Parbat. Located just 8km from K2, Broad Peak offers stunning Karakoram views.",
    timeline: [
      { day: "Day 1-2", title: "Arrival in Islamabad", description: "Arrive in Islamabad. Team meeting, briefing, and gear verification." },
      { day: "Day 3", title: "Fly to Skardu", description: "Fly to Skardu (weather dependent). Enjoy views of the Karakoram Range." },
      { day: "Day 4-5", title: "Skardu Rest Days", description: "Acclimatization and rest in Skardu. Final preparations and shopping." },
      { day: "Day 6-7", title: "Drive to Askole", description: "Jeep journey to Askole. Organize porters and pack animals." },
      { day: "Day 8-14", title: "Trek to Base Camp", description: "Trek through Baltoro Glacier to Broad Peak Base Camp (4,900m)." },
      { day: "Day 15-20", title: "Base Camp Setup", description: "Establish base camp, acclimatization walks, and climbing preparation." },
      { day: "Day 21-35", title: "Rotations to High Camps", description: "Establish Camp 1 (5,700m), Camp 2 (6,400m), and Camp 3 (7,100m)." },
      { day: "Day 36-45", title: "Summit Window", description: "Wait for weather. Summit push to 8,051m via the West Spur route." },
      { day: "Day 46-50", title: "Descent & Trek Out", description: "Descend and pack camps. Trek back to Askole." },
      { day: "Day 51-55", title: "Return Journey", description: "Return to Skardu and fly to Islamabad. Celebration and departure." },
    ],
    servicesIncluded: [
      "All climbing permits and fees",
      "Liaison Officer provision",
      "Experienced climbing guides",
      "Base camp and high camp meals",
      "Camping and climbing equipment",
      "Fixed rope installation",
      "Supplemental oxygen (3 bottles)",
      "Communication equipment",
      "Emergency rescue insurance",
      "Porter and animal transport",
      "Overland transportation",
      "Hotel accommodation",
    ],
    servicesNotIncluded: [
      "International airfare",
      "Personal climbing equipment",
      "Travel insurance",
      "Staff tips and gratuities",
      "Extra oxygen bottles",
      "Personal expenses",
      "Pakistan visa",
      "Weather-related delays",
    ],
    requirements: [
      "Previous 6000m peak experience",
      "Good technical climbing skills",
      "Excellent physical condition",
      "Medical fitness certificate",
      "Mountaineering insurance required",
    ],
    highlights: [
      "Accessible first 8000m peak",
      "Views of K2 from base camp",
      "Trek the famous Baltoro Glacier",
      "Climb in the heart of the Karakoram",
    ],
  },
  {
    id: "spantik",
    slug: "spantik-expedition",
    name: "Spantik Expedition",
    altitude: "7,027m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "25-30 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - August",
    price: 6500,
    groupSize: "4-10 climbers",
    image: heroImage2,
    description: "Spantik, or Golden Peak, rises to 7,027m in the Karakoram. Known for its stunning golden color at sunset, it's an excellent introduction to high-altitude mountaineering.",
    overview: "The Spantik Expedition is ideal for climbers looking to gain experience on 7000m peaks. The normal route via the Southeast Ridge is technically moderate but requires solid mountaineering fundamentals. The peak offers spectacular views of Nanga Parbat, Rakaposhi, and the Karakoram giants.",
    timeline: [
      { day: "Day 1-2", title: "Arrival in Islamabad", description: "Arrive and meet the team. Briefing and gear check." },
      { day: "Day 3", title: "Drive to Gilgit", description: "Scenic drive along the Karakoram Highway to Gilgit." },
      { day: "Day 4", title: "Drive to Arandu", description: "Continue to Arandu village in the Chogo Lungma Valley." },
      { day: "Day 5-8", title: "Trek to Base Camp", description: "4-day trek to Spantik Base Camp (4,500m)." },
      { day: "Day 9-12", title: "Acclimatization", description: "Rest and acclimatization at base camp. Short hikes." },
      { day: "Day 13-20", title: "Summit Rotations", description: "Establish Camp 1 (5,400m) and Camp 2 (6,100m). Summit attempts." },
      { day: "Day 21-25", title: "Summit & Descent", description: "Final summit push and descent to base camp." },
      { day: "Day 26-30", title: "Trek Out & Return", description: "Trek to road head and return to Islamabad." },
    ],
    servicesIncluded: [
      "Climbing and trekking permits",
      "Professional mountain guide",
      "All meals during expedition",
      "Camping equipment",
      "Fixed ropes where needed",
      "Porter services",
      "Ground transportation",
      "Hotel accommodation in cities",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal climbing gear",
      "Travel insurance",
      "Tips for staff",
      "Personal expenses",
      "Visa fees",
    ],
    requirements: [
      "Previous high altitude trekking experience",
      "Basic mountaineering skills",
      "Good physical fitness",
      "Medical clearance",
    ],
    highlights: [
      "Perfect 7000m training peak",
      "Stunning 'Golden Peak' sunset views",
      "Views of Karakoram giants",
      "Experience authentic mountain culture",
    ],
  },
  {
    id: "k2-gondogoro-trek",
    slug: "k2-gondogoro-trek",
    name: "K2 and Gondogoro La Trek",
    altitude: "5,128m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "14-16 Days",
    difficulty: "Difficult",
    bestSeason: "June - September",
    price: 1800,
    groupSize: "4-12 trekkers",
    image: heroImage1,
    description: "Trek to K2 Base Camp and cross the scenic Gondogoro La pass with stunning views of the Karakoram Range.",
    overview: "This challenging trek combines the iconic K2 Base Camp trek with a crossing of Gondogoro La (5,128m), offering spectacular alpine scenery and access to remote mountain regions.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad to Skardu", description: "Arrive and travel to Skardu" },
      { day: "Day 3-4", title: "Skardu Preparation", description: "Organize supplies and permits" },
      { day: "Day 5-11", title: "Trek to K2 Base Camp", description: "Trek through Baltoro Glacier to K2 BC" },
      { day: "Day 12-14", title: "Gondogoro La Pass", description: "Cross the scenic pass and descend" },
      { day: "Day 15-16", title: "Return to Islamabad", description: "Return journey to Islamabad" },
    ],
    servicesIncluded: ["Trekking permits", "Professional guides", "All meals", "Camping equipment", "Porter services", "Transportation"],
    servicesNotIncluded: ["International flights", "Personal gear", "Travel insurance", "Tips", "Personal expenses"],
    requirements: ["Good physical fitness", "Trekking experience", "Medical clearance"],
    highlights: ["K2 Base Camp views", "Alpine pass crossing", "Stunning glacier scenery"],
  },
  {
    id: "k2-base-camp-trek",
    slug: "k2-base-camp-trek",
    name: "K2 Base Camp Trek",
    altitude: "5,150m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "12-14 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - September",
    price: 1500,
    groupSize: "4-12 trekkers",
    image: heroImage2,
    description: "Trek to the base camp of K2, the world's second highest mountain, via the legendary Baltoro Glacier.",
    overview: "Experience the majesty of K2 Base Camp on this iconic trek through the Karakoram, featuring the world's longest glacier outside the polar regions.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad to Skardu", description: "Arrive and travel to Skardu" },
      { day: "Day 3-4", title: "Skardu Rest", description: "Acclimatization in Skardu" },
      { day: "Day 5-11", title: "Baltoro Trek", description: "Trek via Jola, Paiju, Urdukas to K2 BC" },
      { day: "Day 12-14", title: "Return Journey", description: "Return to Islamabad" },
    ],
    servicesIncluded: ["Trekking permits", "Professional guides", "All meals", "Camping equipment", "Porter services"],
    servicesNotIncluded: ["International flights", "Personal gear", "Travel insurance", "Tips"],
    requirements: ["Moderate physical fitness", "Trekking experience", "Acclimatization readiness"],
    highlights: ["K2 Base Camp", "Baltoro Glacier", "Concordia views", "Alpine scenery"],
  },
  {
    id: "five-8000m-base-camp",
    slug: "five-8000m-base-camp-trek",
    name: "Five 8000m Base Camp Trek",
    altitude: "5,200m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "16-18 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - September",
    price: 2200,
    groupSize: "4-10 trekkers",
    image: heroImage1,
    description: "Visit base camps of five 8000m peaks: K2, Broad Peak, Gasherbrum I & II, and a stunning alpine experience.",
    overview: "An exclusive trek visiting the base camps of multiple 8000m peaks, showcasing the heart of the Karakoram Range and its majestic mountains.",
    timeline: [
      { day: "Day 1-4", title: "Islamabad to Base Camps", description: "Travel and preparation" },
      { day: "Day 5-14", title: "Multi Base Camp Trek", description: "Visit five different base camps" },
      { day: "Day 15-18", title: "Return to Islamabad", description: "Return journey" },
    ],
    servicesIncluded: ["Trekking permits", "Expert guides", "Full meals", "Equipment", "Porters", "Transportation"],
    servicesNotIncluded: ["International flights", "Personal gear", "Insurance", "Tips"],
    requirements: ["Excellent fitness", "High altitude experience", "Medical clearance"],
    highlights: ["Multiple 8000m peaks", "Baltoro Glacier", "Alpine adventure"],
  },
  {
    id: "nanga-parbat-base-camp-trek",
    slug: "nanga-parbat-base-camp-trek",
    name: "Nanga Parbat Base Camp Trek",
    altitude: "4,100m",
    location: "Diamer District, Pakistan",
    duration: "10-12 Days",
    difficulty: "Difficult",
    bestSeason: "June - September",
    price: 1300,
    groupSize: "4-10 trekkers",
    image: heroImage2,
    description: "Trek to the base camp of Nanga Parbat, the 9th highest mountain in the world, via the scenic Diamir valley.",
    overview: "A challenging trek featuring dramatic mountain scenery and access to one of the world's most impressive peaks from the Diamir Face.",
    timeline: [
      { day: "Day 1-2", title: "Travel to Chilas", description: "Journey from Islamabad" },
      { day: "Day 3-8", title: "Trek to Base Camp", description: "Trek through Diamir valley" },
      { day: "Day 9-12", title: "Exploration & Return", description: "Base camp views and return" },
    ],
    servicesIncluded: ["Permits", "Guides", "Meals", "Equipment", "Porters"],
    servicesNotIncluded: ["Flights", "Gear", "Insurance", "Tips"],
    requirements: ["Good fitness", "Trekking experience"],
    highlights: ["Nanga Parbat views", "Diamir valley", "High altitude scenery"],
  },
  {
    id: "fairy-meadows-trek",
    slug: "fairy-meadows-trek",
    name: "Fairy Meadows Trek",
    altitude: "3,300m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "8-10 Days",
    difficulty: "Moderate",
    bestSeason: "May - September",
    price: 900,
    groupSize: "4-15 trekkers",
    image: heroImage1,
    description: "Trek through lush alpine meadows with spectacular views of Nanga Parbat, the 'Killer Mountain'.",
    overview: "A scenic trek to the famous Fairy Meadows offering close-up views of Nanga Parbat and picturesque mountain landscape.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad to Base", description: "Travel and preparation" },
      { day: "Day 3-7", title: "Meadows Trek", description: "Trek through alpine meadows" },
      { day: "Day 8-10", title: "Return", description: "Return to Islamabad" },
    ],
    servicesIncluded: ["Permits", "Guides", "Meals", "Equipment", "Porters"],
    servicesNotIncluded: ["Flights", "Gear", "Insurance"],
    requirements: ["Basic fitness", "Moderate experience"],
    highlights: ["Nanga Parbat views", "Alpine meadows", "Scenic photography"],
  },
  {
    id: "around-nanga-parbat-trek",
    slug: "around-nanga-parbat-trek",
    name: "Around Nanga Parbat Trek",
    altitude: "4,500m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "14-16 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - August",
    price: 1900,
    groupSize: "4-8 trekkers",
    image: heroImage2,
    description: "Circumnavigate Nanga Parbat, experiencing diverse valleys and mountain scenery from all angles.",
    overview: "A rarely attempted trek that circles Nanga Parbat, providing unique perspectives of the 'Killer Mountain' and remote Himalayan valleys.",
    timeline: [
      { day: "Day 1-3", title: "Preparation", description: "Travel and setup" },
      { day: "Day 4-13", title: "Circuit Trek", description: "Trek around Nanga Parbat" },
      { day: "Day 14-16", title: "Return", description: "Return journey" },
    ],
    servicesIncluded: ["Permits", "Expert guides", "Meals", "Equipment", "Porters"],
    servicesNotIncluded: ["Flights", "Gear", "Insurance", "Tips"],
    requirements: ["Excellent fitness", "High altitude experience", "Technical skills"],
    highlights: ["360-degree views", "Remote valleys", "Alpine adventure"],
  },
  {
    id: "nangma-valley-trek",
    slug: "nangma-valley-trek",
    name: "Nangma Valley Trek",
    altitude: "3,800m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "9-11 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - September",
    price: 1100,
    groupSize: "4-12 trekkers",
    image: heroImage1,
    description: "Trek through the pristine Nangma Valley with views of surrounding peaks and traditional mountain villages.",
    overview: "An off-the-beaten-path trek offering authentic mountain culture, stunning scenery, and interaction with local communities.",
    timeline: [
      { day: "Day 1-2", title: "Travel", description: "Journey to valley base" },
      { day: "Day 3-8", title: "Valley Trek", description: "Trek through Nangma Valley" },
      { day: "Day 9-11", title: "Return", description: "Return to Islamabad" },
    ],
    servicesIncluded: ["Permits", "Guides", "Meals", "Equipment", "Porters"],
    servicesNotIncluded: ["Flights", "Gear", "Insurance"],
    requirements: ["Moderate fitness", "Cultural appreciation"],
    highlights: ["Valley scenery", "Local villages", "Mountain culture"],
  },
  {
    id: "thalle-la-trek",
    slug: "thalle-la-trek",
    name: "Thalle La Trek",
    altitude: "4,600m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "11-13 Days",
    difficulty: "Difficult",
    bestSeason: "June - August",
    price: 1400,
    groupSize: "4-10 trekkers",
    image: heroImage2,
    description: "Trek over Thalle La pass with panoramic views of multiple Karakoram peaks and pristine alpine terrain.",
    overview: "A high mountain pass trek offering dramatic alpine scenery, technical terrain, and stunning mountain vistas.",
    timeline: [
      { day: "Day 1-3", title: "Preparation", description: "Travel and acclimatization" },
      { day: "Day 4-10", title: "Pass Trek", description: "Trek to and cross Thalle La" },
      { day: "Day 11-13", title: "Return", description: "Return journey" },
    ],
    servicesIncluded: ["Permits", "Guides", "Meals", "Equipment", "Porters"],
    servicesNotIncluded: ["Flights", "Gear", "Insurance"],
    requirements: ["Good fitness", "Alpine experience", "Technical ability"],
    highlights: ["Mountain pass", "Alpine scenery", "Peak views"],
  },
  {
    id: "snow-lake-hispar-trek",
    slug: "snow-lake-hispar-trek",
    name: "Snow Lake - Hispar La Trek",
    altitude: "5,151m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "15-17 Days",
    difficulty: "Very Difficult",
    bestSeason: "July - September",
    price: 2000,
    groupSize: "4-10 trekkers",
    image: heroImage1,
    description: "Cross two major mountain passes via Snow Lake with traverse of alpine glaciers and Hispar La pass.",
    overview: "A challenging high-altitude trek crossing multiple glaciers and passes through the heart of the Karakoram Range.",
    timeline: [
      { day: "Day 1-3", title: "Travel", description: "Journey to trek base" },
      { day: "Day 4-13", title: "Glacier Trek", description: "Cross Snow Lake and Hispar La" },
      { day: "Day 14-17", title: "Return", description: "Return to Islamabad" },
    ],
    servicesIncluded: ["Permits", "Expert guides", "Meals", "Equipment", "Porters"],
    servicesNotIncluded: ["Flights", "Gear", "Insurance", "Tips"],
    requirements: ["Excellent fitness", "High altitude experience", "Technical skills required"],
    highlights: ["Glacier crossing", "Mountain passes", "Alpine wilderness"],
  },
  {
    id: "pastore-peak-trek",
    slug: "pastore-peak-trek",
    name: "Pastore Peak Trek",
    altitude: "4,708m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "10-12 Days",
    difficulty: "Difficult",
    bestSeason: "June - September",
    price: 1300,
    groupSize: "4-10 trekkers",
    image: heroImage2,
    description: "Trek and climb Pastore Peak with sweeping views of the Karakoram and Hindukush ranges.",
    overview: "A trek combining mountaineering with scenic alpine hiking, offering stunning panoramic views from the summit.",
    timeline: [
      { day: "Day 1-2", title: "Travel", description: "Journey to base" },
      { day: "Day 3-8", title: "Peak Trek", description: "Trek to and climb Pastore Peak" },
      { day: "Day 9-12", title: "Return", description: "Return journey" },
    ],
    servicesIncluded: ["Permits", "Guides", "Meals", "Equipment", "Porters"],
    servicesNotIncluded: ["Flights", "Gear", "Insurance"],
    requirements: ["Good fitness", "Climbing experience"],
    highlights: ["Peak summit", "Panoramic views", "Alpine climbing"],
  },
  {
    id: "shimshal-pass-trek",
    slug: "shimshal-pass-trek",
    name: "Shimshal Pass Trek",
    altitude: "4,720m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "12-14 Days",
    difficulty: "Very Difficult",
    bestSeason: "July - September",
    price: 1700,
    groupSize: "4-8 trekkers",
    image: heroImage1,
    description: "Trek through remote Shimshal Valley and cross the high Shimshal Pass with stunning mountain scenery.",
    overview: "An adventurous trek through one of the most remote regions of the Karakoram, crossing a scenic high-altitude pass.",
    timeline: [
      { day: "Day 1-2", title: "Travel", description: "Journey to Shimshal Valley" },
      { day: "Day 3-10", title: "Valley Trek", description: "Trek through valley to pass" },
      { day: "Day 11-14", title: "Pass Crossing & Return", description: "Cross pass and return" },
    ],
    servicesIncluded: ["Permits", "Expert guides", "Meals", "Equipment", "Porters"],
    servicesNotIncluded: ["Flights", "Gear", "Insurance", "Tips"],
    requirements: ["Excellent fitness", "High altitude experience", "Remote area trekking"],
    highlights: ["Remote valley", "High pass", "Mountain wilderness"],
  },
  {
    id: "gasherbrum-iii",
    slug: "gasherbrum-iii-expedition",
    name: "Gasherbrum III Expedition",
    altitude: "7,952m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "40-45 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - August",
    price: 28000,
    groupSize: "4-8 climbers",
    image: heroImage1,
    description: "Gasherbrum III at 7,952m is the 15th highest mountain in the world. A challenging yet rewarding 7000m expedition.",
    overview: "The Gasherbrum III Expedition offers an excellent intermediate challenge between 6000m training peaks and 8000m summits. Located in the Karakoram, it provides spectacular alpine experiences with well-established climbing routes.",
    timeline: [
      { day: "Day 1-2", title: "Arrival & Briefing", description: "Arrive in Islamabad for expedition briefing and final preparations." },
      { day: "Day 3", title: "Fly to Skardu", description: "Scenic flight to Skardu with panoramic mountain views." },
      { day: "Day 4-5", title: "Skardu Acclimatization", description: "Rest and acclimatization in Skardu with final gear checks." },
      { day: "Day 6-7", title: "Drive to Askole", description: "Jeep journey to Askole and porter organization." },
      { day: "Day 8-14", title: "Trek to Base Camp", description: "7-day trek through Baltoro Glacier to Gasherbrum Base Camp." },
      { day: "Day 15-20", title: "Base Camp Setup", description: "Establish base camp and acclimatization hikes." },
      { day: "Day 21-35", title: "Camp Rotations", description: "Establish higher camps with progressive acclimatization climbs." },
      { day: "Day 36-42", title: "Summit Window", description: "Wait for optimal weather and summit push." },
      { day: "Day 43-45", title: "Descent & Return", description: "Descend and trek back to Askole, return to Islamabad." },
    ],
    servicesIncluded: ["Climbing permits", "Liaison Officer", "Professional guides", "All meals", "Camping equipment", "Fixed ropes", "Emergency communication", "Porter services", "Ground transportation"],
    servicesNotIncluded: ["International flights", "Personal climbing gear", "Travel insurance", "Staff tips", "Personal expenses"],
    requirements: ["Previous 6000m+ experience", "Technical climbing skills", "Excellent physical fitness", "Medical clearance"],
    highlights: ["Climb a technical 7000m peak", "Experience Baltoro Glacier", "Alpine climbing adventure", "Spectacular Karakoram views"],
  },
  {
    id: "gasherbrum-iv",
    slug: "gasherbrum-iv-expedition",
    name: "Gasherbrum IV Expedition",
    altitude: "7,932m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "40-45 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - August",
    price: 28500,
    groupSize: "4-8 climbers",
    image: heroImage2,
    description: "Gasherbrum IV at 7,932m is a challenging Alpine climb offering technical mountaineering experience in the Karakoram Range.",
    overview: "The Gasherbrum IV Expedition combines technical climbing with high-altitude mountaineering. This peak is ideal for climbers seeking their first 7000m+ summit after completing 6000m peaks.",
    timeline: [
      { day: "Day 1-2", title: "Arrival in Islamabad", description: "Team briefing and expedition orientation in Islamabad." },
      { day: "Day 3", title: "Flight to Skardu", description: "Morning flight to Skardu with stunning mountain views." },
      { day: "Day 4-5", title: "Skardu Rest Days", description: "Acclimatization and final preparations in Skardu." },
      { day: "Day 6-7", title: "Drive to Askole", description: "Scenic jeep journey and porter organization." },
      { day: "Day 8-14", title: "Baltoro Trek", description: "Trek to Gasherbrum Base Camp via Baltoro Glacier." },
      { day: "Day 15-20", title: "Base Camp Establishment", description: "Set up base camp and begin acclimatization." },
      { day: "Day 21-35", title: "Higher Camp Rotations", description: "Establish camps with multiple acclimatization climbs." },
      { day: "Day 36-42", title: "Summit Push", description: "Wait for weather window and summit attempt." },
      { day: "Day 43-45", title: "Descent & Return", description: "Descend camps and return to Islamabad." },
    ],
    servicesIncluded: ["Permits and royalties", "Liaison Officer", "Expert guides", "All meals", "High-altitude tents", "Fixed ropes", "Communication equipment", "Porter services", "Transportation"],
    servicesNotIncluded: ["International airfare", "Personal climbing gear", "Insurance policies", "Staff gratuities", "Personal expenses"],
    requirements: ["6000m climbing experience", "Advanced technical skills", "Superior physical conditioning", "Medical fitness clearance"],
    highlights: ["Technical 7000m peak", "Alpine climbing experience", "Remote mountain adventure", "Karakoram wilderness"],
  },
  {
    id: "masherbrum",
    slug: "masherbrum-expedition",
    name: "Masherbrum Expedition",
    altitude: "7,806m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "35-40 Days",
    difficulty: "Difficult",
    bestSeason: "June - August",
    price: 26000,
    groupSize: "4-10 climbers",
    image: heroImage1,
    description: "Masherbrum at 7,806m offers a technically moderate 7000m peak with excellent mountaineering training value.",
    overview: "The Masherbrum Expedition provides an ideal transition climb for mountaineers moving from 6000m to 8000m peaks. The mountain offers good climbing conditions and stunning views of the Karakoram Range.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Arrival", description: "Team gathering and expedition briefing." },
      { day: "Day 3", title: "Fly to Skardu", description: "Flight to Skardu with mountain panoramas." },
      { day: "Day 4-5", title: "Skardu Preparation", description: "Organize supplies and acclimatize in Skardu." },
      { day: "Day 6-7", title: "Jeep to Askole", description: "Travel to Askole and porter coordination." },
      { day: "Day 8-12", title: "Trek to Base Camp", description: "Trek to Masherbrum Base Camp." },
      { day: "Day 13-18", title: "Base Camp Setup", description: "Establish base camp and acclimatization walks." },
      { day: "Day 19-32", title: "Camp Establishment", description: "Set up higher camps with climbing rotations." },
      { day: "Day 33-38", title: "Summit Push", description: "Summit attempt during favorable weather window." },
      { day: "Day 39-40", title: "Descent & Departure", description: "Descend and return to Islamabad." },
    ],
    servicesIncluded: ["Climbing permits", "Liaison Officer", "Professional guides", "All meals", "Camping equipment", "Ropes and anchors", "Communication gear", "Porter services"],
    servicesNotIncluded: ["International flights", "Personal equipment", "Insurance", "Tips and gratuities", "Personal costs"],
    requirements: ["Good 6000m experience", "Solid technical skills", "Strong cardiovascular fitness", "Medical clearance"],
    highlights: ["Excellent training 7000m peak", "Technical climbing", "Karakoram adventure", "Alpine mountaineering"],
  },
  {
    id: "chogolisa",
    slug: "chogolisa-expedition",
    name: "Chogolisa Expedition",
    altitude: "7,668m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "35-40 Days",
    difficulty: "Difficult",
    bestSeason: "June - August",
    price: 25500,
    groupSize: "4-10 climbers",
    image: heroImage2,
    description: "Chogolisa at 7,668m is one of the more accessible 7000m peaks, ideal for mountaineers gaining high-altitude experience.",
    overview: "The Chogolisa Expedition offers an excellent stepping stone to 8000m peaks. Known for its relatively moderate technical difficulty and good success rates, Chogolisa is perfect for climbers building their high-altitude portfolio.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Briefing", description: "Expedition team orientation and final briefings." },
      { day: "Day 3", title: "Skardu Flight", description: "Morning flight to Skardu." },
      { day: "Day 4-5", title: "Skardu Rest", description: "Acclimatization and preparation in Skardu." },
      { day: "Day 6-7", title: "Askole Journey", description: "Drive to Askole and organize porters." },
      { day: "Day 8-12", title: "Base Camp Trek", description: "Trek to Chogolisa Base Camp." },
      { day: "Day 13-18", title: "Base Camp Acclimatization", description: "Establish camp and acclimatization hikes." },
      { day: "Day 19-32", title: "Higher Camp Climbs", description: "Progressive camps with climbing rotations." },
      { day: "Day 33-38", title: "Summit Window", description: "Await weather and summit attempt." },
      { day: "Day 39-40", title: "Descent & Return", description: "Descend and return to Islamabad." },
    ],
    servicesIncluded: ["Permits and royalties", "Liaison Officer", "Expert guides", "Full meals", "Tents and equipment", "Fixed ropes", "Radio communication", "Porters", "Transportation"],
    servicesNotIncluded: ["International flights", "Personal gear", "Insurance", "Staff tips", "Personal expenses"],
    requirements: ["Previous 6000m experience", "Good technical climbing", "Excellent fitness", "Medical clearance"],
    highlights: ["Accessible 7000m peak", "Good training mountain", "Spectacular views", "High success rates"],
  },
  {
    id: "k6",
    slug: "k6-expedition",
    name: "K6 Expedition",
    altitude: "7,462m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "30-35 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - August",
    price: 23000,
    groupSize: "4-10 climbers",
    image: heroImage1,
    description: "K6 at 7,462m is one of the most accessible 7000m peaks in the Karakoram, ideal for ambitious high-altitude mountaineers.",
    overview: "The K6 Expedition is perfect for climbers seeking their first 7000m summit or those training for higher peaks. The mountain offers moderate technical difficulty with good climbing routes and high success rates.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Arrival", description: "Team briefing and preparation." },
      { day: "Day 3", title: "Skardu Flight", description: "Flight to Skardu." },
      { day: "Day 4-5", title: "Skardu Acclimatization", description: "Rest and acclimatization in Skardu." },
      { day: "Day 6-7", title: "Askole Drive", description: "Jeep to Askole and porter setup." },
      { day: "Day 8-11", title: "Base Camp Trek", description: "Trek to K6 Base Camp." },
      { day: "Day 12-17", title: "Base Camp Rest", description: "Establish camp and acclimatize." },
      { day: "Day 18-28", title: "Camp Climbs", description: "Establish camps with multiple rotations." },
      { day: "Day 29-33", title: "Summit & Descent", description: "Summit push and descent." },
      { day: "Day 34-35", title: "Return Journey", description: "Return to Islamabad." },
    ],
    servicesIncluded: ["Permits", "Liaison Officer", "Professional guides", "All meals", "Equipment", "Fixed ropes", "Communication", "Porters", "Transportation"],
    servicesNotIncluded: ["International flights", "Personal gear", "Insurance", "Tips", "Personal spending"],
    requirements: ["5000m+ climbing experience", "Basic technical skills", "Good physical fitness", "Medical approval"],
    highlights: ["Accessible 7000m peak", "Perfect first 7000m mountain", "Great views", "Good success rates"],
  },
  {
    id: "rakaposhi",
    slug: "rakaposhi-expedition",
    name: "Rakaposhi Expedition",
    altitude: "7,788m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "30-35 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "May - September",
    price: 24000,
    groupSize: "4-10 climbers",
    image: heroImage2,
    description: "Rakaposhi at 7,788m dominates the Hunza valley with its spectacular pyramid. A technically moderate 7000m peak with excellent views.",
    overview: "The Rakaposhi Expedition is ideal for mountaineers seeking a relatively straightforward 7000m climb with stunning mountain scenery. The peak's proximity to civilization and moderate technical demands make it accessible yet rewarding.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Briefing", description: "Team orientation and final preparations." },
      { day: "Day 3-4", title: "Drive to Hunza", description: "Drive from Islamabad to Hunza Valley." },
      { day: "Day 5", title: "Hunza Rest", description: "Rest and acclimatization in Hunza." },
      { day: "Day 6-8", title: "Base Camp Trek", description: "Trek to Rakaposhi Base Camp." },
      { day: "Day 9-15", title: "Base Camp Acclimatization", description: "Establish camp and acclimatization hikes." },
      { day: "Day 16-28", title: "Higher Camp Climbs", description: "Establish camps with climbing rotations." },
      { day: "Day 29-32", title: "Summit Push", description: "Summit attempt during weather window." },
      { day: "Day 33-35", title: "Return", description: "Descent and return to Islamabad." },
    ],
    servicesIncluded: ["Permits and royalties", "Liaison Officer", "Experienced guides", "All meals", "High-altitude equipment", "Fixed ropes", "Communication equipment", "Porter services", "Ground transportation"],
    servicesNotIncluded: ["International flights", "Personal climbing gear", "Travel insurance", "Staff gratuities", "Personal expenses"],
    requirements: ["Previous 6000m experience", "Good technical climbing ability", "Excellent physical condition", "Medical fitness certificate"],
    highlights: ["Spectacular Hunza Valley views", "Accessible 7000m climb", "Moderate technical difficulty", "Great training mountain"],
  },
  {
    id: "laila-peak",
    slug: "laila-peak-expedition",
    name: "Laila Peak Expedition",
    altitude: "6,096m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "25-30 Days",
    difficulty: "Moderate",
    bestSeason: "June - August",
    price: 18000,
    groupSize: "4-10 climbers",
    image: heroImage1,
    description: "Laila Peak at 6,096m offers an excellent introduction to high-altitude mountaineering in the Karakoram Range.",
    overview: "The Laila Peak Expedition is ideal for climbers new to alpine mountaineering or those seeking additional acclimatization experience. The peak offers good climbing routes and stunning views of the surrounding mountains.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Briefing", description: "Team orientation and expedition briefing." },
      { day: "Day 3", title: "Flight to Skardu", description: "Scenic flight to Skardu." },
      { day: "Day 4-5", title: "Skardu Preparation", description: "Acclimatization and gear preparation in Skardu." },
      { day: "Day 6-7", title: "Askole Journey", description: "Drive to Askole and organize porters." },
      { day: "Day 8-11", title: "Base Camp Trek", description: "Trek to Laila Peak Base Camp." },
      { day: "Day 12-17", title: "Base Camp Acclimatization", description: "Establish camp and acclimatization climbs." },
      { day: "Day 18-25", title: "Camp Setup & Climbs", description: "Set up higher camps with climbing rotations." },
      { day: "Day 26-28", title: "Summit Push", description: "Summit attempt during favorable weather." },
      { day: "Day 29-30", title: "Descent & Return", description: "Descend and return to Islamabad." },
    ],
    servicesIncluded: ["Permits", "Liaison Officer", "Professional guides", "All meals", "Equipment", "Fixed ropes", "Communication gear", "Porter services"],
    servicesNotIncluded: ["International flights", "Personal climbing gear", "Insurance", "Tips and gratuities", "Personal expenses"],
    requirements: ["Good physical fitness", "Basic mountaineering skills", "Previous trekking experience", "Medical clearance"],
    highlights: ["Excellent training 6000m peak", "Good climbing routes", "Stunning alpine views", "Ideal first high peak"],
  },
  {
    id: "pastore-peak",
    slug: "pastore-peak-expedition",
    name: "Pastore Peak Expedition",
    altitude: "6,618m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "28-32 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - August",
    price: 20000,
    groupSize: "4-8 climbers",
    image: heroImage2,
    description: "Pastore Peak at 6,618m combines mountaineering with technical climbing for an intermediate mountain experience.",
    overview: "The Pastore Peak Expedition offers an excellent stepping stone for climbers progressing toward 7000m peaks. The mountain features moderate technical climbing with panoramic views of the Karakoram and Hindu Kush ranges.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Arrival", description: "Team briefing and expedition orientation." },
      { day: "Day 3", title: "Skardu Flight", description: "Flight to Skardu with mountain views." },
      { day: "Day 4-5", title: "Skardu Rest", description: "Acclimatization and preparation." },
      { day: "Day 6-7", title: "Askole Drive", description: "Travel to Askole and porter setup." },
      { day: "Day 8-12", title: "Base Camp Trek", description: "Trek to Pastore Peak Base Camp." },
      { day: "Day 13-18", title: "Base Camp Acclimatization", description: "Establish camp and acclimatization hikes." },
      { day: "Day 19-28", title: "Higher Camp Climbs", description: "Establish camps with multiple rotations." },
      { day: "Day 29-31", title: "Summit Push", description: "Summit attempt during weather window." },
      { day: "Day 32", title: "Return", description: "Descent and return to Islamabad." },
    ],
    servicesIncluded: ["Permits and royalties", "Liaison Officer", "Expert guides", "All meals", "High-altitude equipment", "Fixed ropes", "Communication", "Porters"],
    servicesNotIncluded: ["International flights", "Personal gear", "Insurance", "Staff tips", "Personal costs"],
    requirements: ["5000m+ climbing experience", "Solid technical climbing skills", "Good physical fitness", "Medical clearance"],
    highlights: ["Technical 6000m climb", "Great training mountain", "Panoramic views", "Karakoram adventure"],
  },
  {
    id: "khusrogang",
    slug: "khusrogang-expedition",
    name: "Khusrogang Expedition",
    altitude: "6,400m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "26-30 Days",
    difficulty: "Moderate",
    bestSeason: "June - August",
    price: 19000,
    groupSize: "4-10 climbers",
    image: heroImage1,
    description: "Khusrogang at 6,400m provides an excellent training ground for higher altitude climbing with moderate technical difficulty.",
    overview: "The Khusrogang Expedition is perfect for mountaineers building experience toward 7000m peaks. The mountain offers accessible climbing routes with good acclimatization opportunities and spectacular mountain scenery.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Briefing", description: "Team gathering and final briefings." },
      { day: "Day 3", title: "Skardu Flight", description: "Flight to Skardu." },
      { day: "Day 4-5", title: "Skardu Acclimatization", description: "Rest and acclimatization in Skardu." },
      { day: "Day 6-7", title: "Askole Journey", description: "Drive to Askole and organize logistics." },
      { day: "Day 8-11", title: "Base Camp Trek", description: "Trek to Khusrogang Base Camp." },
      { day: "Day 12-17", title: "Base Camp Setup", description: "Establish camp and acclimatization activities." },
      { day: "Day 18-26", title: "Camp Establishment", description: "Set up higher camps with climbing rotations." },
      { day: "Day 27-29", title: "Summit Window", description: "Summit attempt during favorable weather." },
      { day: "Day 30", title: "Descent", description: "Descend and return to Islamabad." },
    ],
    servicesIncluded: ["Climbing permits", "Liaison Officer", "Experienced guides", "All meals", "Camping equipment", "Fixed ropes", "Radio communication", "Porter services"],
    servicesNotIncluded: ["International flights", "Personal climbing equipment", "Insurance", "Staff gratuities", "Personal spending"],
    requirements: ["Previous 5000m+ experience", "Intermediate technical skills", "Strong physical fitness", "Medical approval"],
    highlights: ["Moderate 6000m peak", "Good training mountain", "Accessible climbing", "Alpine mountain views"],
  },
  {
    id: "gondogoro-peak",
    slug: "gondogoro-peak-expedition",
    name: "Gondogoro Peak Expedition",
    altitude: "5,950m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "22-26 Days",
    difficulty: "Moderate",
    bestSeason: "June - August",
    price: 17500,
    groupSize: "4-10 climbers",
    image: heroImage2,
    description: "Gondogoro Peak at 5,950m is one of the most accessible high-altitude peaks, ideal for building mountain climbing experience.",
    overview: "The Gondogoro Peak Expedition offers an excellent introduction to high-altitude climbing with minimal technical difficulty. Perfect for climbers new to the Karakoram or those seeking their first significant altitude climb.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Orientation", description: "Team briefing and expedition preparation." },
      { day: "Day 3", title: "Skardu Flight", description: "Flight to Skardu." },
      { day: "Day 4-5", title: "Skardu Rest", description: "Acclimatization in Skardu." },
      { day: "Day 6-7", title: "Askole Drive", description: "Drive to Askole." },
      { day: "Day 8-10", title: "Base Camp Trek", description: "Trek to Gondogoro Base Camp." },
      { day: "Day 11-16", title: "Base Camp Acclimatization", description: "Establish camp and altitude acclimatization." },
      { day: "Day 17-22", title: "Higher Camp Climbs", description: "Set up camps and climbing rotations." },
      { day: "Day 23-24", title: "Summit Push", description: "Summit attempt during weather window." },
      { day: "Day 25-26", title: "Return", description: "Descend and return to Islamabad." },
    ],
    servicesIncluded: ["Permits", "Liaison Officer", "Professional guides", "All meals", "Equipment", "Fixed ropes", "Communication", "Porters"],
    servicesNotIncluded: ["International flights", "Personal gear", "Insurance", "Tips", "Personal spending"],
    requirements: ["Good physical fitness", "Basic mountaineering experience", "High altitude trekking background", "Medical clearance"],
    highlights: ["Accessible 6000m peak", "Ideal training mountain", "Minimal technical difficulty", "Great introduction to mountaineering"],
  },
  {
    id: "trango-tower",
    slug: "trango-tower",
    name: "Trango Tower Climbing",
    altitude: "6,286m",
    location: "Karakoram, Gilgit Baltistan, Pakistan",
    duration: "20-25 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - September",
    price: 22000,
    groupSize: "2-6 climbers",
    image: heroImage1,
    description: "Trango Tower is one of the most challenging and iconic rock climbing destinations in the world, featuring pristine granite walls.",
    overview: "The Trango Tower Climbing expedition offers world-class rock climbing on one of the most magnificent granite towers. This advanced technical climb requires serious mountaineering and rock climbing expertise.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Briefing", description: "Team gathering and expedition preparation." },
      { day: "Day 3", title: "Skardu Flight", description: "Fly to Skardu." },
      { day: "Day 4-5", title: "Skardu Preparation", description: "Organize equipment and logistics." },
      { day: "Day 6-7", title: "Askole Journey", description: "Travel to Askole base village." },
      { day: "Day 8-11", title: "Trek to Base Camp", description: "Trek to Trango Base Camp via Baltoro Glacier." },
      { day: "Day 12-20", title: "Climbing & Acclimatization", description: "Rock climbing and technical training on various pitches." },
      { day: "Day 21-24", title: "Tower Attempt", description: "Climb Trango Tower with multiple advanced pitches." },
      { day: "Day 25", title: "Return", description: "Descent and return to Islamabad." },
    ],
    servicesIncluded: ["Permits", "Expert climbing guides", "Base camp equipment", "All meals", "Fixed ropes", "Communication gear", "Porter services"],
    servicesNotIncluded: ["International flights", "Personal climbing gear", "Insurance", "Staff tips", "Personal expenses"],
    requirements: ["Advanced rock climbing experience", "Previous 5.10+ climbing background", "Excellent physical fitness", "Technical mountaineering skills"],
    highlights: ["Iconic granite tower", "World-class climbing", "Advanced technical routes", "Alpine adventure"],
  },
  {
    id: "great-tower",
    slug: "great-tower",
    name: "Great Tower Climbing",
    altitude: "5,971m",
    location: "Karakoram, Gilgit Baltistan, Pakistan",
    duration: "18-22 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - September",
    price: 20000,
    groupSize: "2-6 climbers",
    image: heroImage2,
    description: "Great Tower offers challenging rock climbing with stunning Karakoram views and technical alpine routes.",
    overview: "The Great Tower Climbing expedition combines technical rock climbing with alpine mountaineering. A fantastic objective for climbers seeking to develop advanced skills in high-altitude rock climbing.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Arrival", description: "Team briefing and preparations." },
      { day: "Day 3", title: "Skardu Flight", description: "Flight to Skardu." },
      { day: "Day 4-5", title: "Skardu Rest", description: "Acclimatization and gear organization." },
      { day: "Day 6-7", title: "Askole Drive", description: "Travel to Askole." },
      { day: "Day 8-10", title: "Base Camp Trek", description: "Trek to Great Tower Base Camp." },
      { day: "Day 11-18", title: "Climbing Days", description: "Technical climbing on various rock pitches." },
      { day: "Day 19-21", title: "Tower Climb", description: "Summit attempt on Great Tower." },
      { day: "Day 22", title: "Return", description: "Descent and return journey." },
    ],
    servicesIncluded: ["Permits", "Rock climbing guides", "Base camp setup", "All meals", "Climbing equipment", "Communication", "Porters"],
    servicesNotIncluded: ["International flights", "Personal climbing gear", "Insurance", "Tips", "Personal costs"],
    requirements: ["Advanced rock climbing skills", "5.9-5.10 climbing experience", "Alpine mountaineering experience", "Technical ability"],
    highlights: ["Excellent rock climbing", "Alpine environment", "Advanced technical routes", "Karakoram wilderness"],
  },
  {
    id: "amin-braq",
    slug: "amin-braq",
    name: "Amin Braq Climbing",
    altitude: "5,610m",
    location: "Charakusa Valley, Gilgit Baltistan, Pakistan",
    duration: "16-20 Days",
    difficulty: "Difficult",
    bestSeason: "June - September",
    price: 18000,
    groupSize: "2-8 climbers",
    image: heroImage1,
    description: "Amin Braq in the Charakusa Valley offers excellent rock climbing with multiple route options and stunning alpine scenery.",
    overview: "The Amin Braq Climbing expedition provides superb rock climbing in a pristine alpine environment. Perfect for climbers developing technical skills with several challenging pitches and beautiful Karakoram views.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Briefing", description: "Team orientation." },
      { day: "Day 3", title: "Skardu Flight", description: "Fly to Skardu." },
      { day: "Day 4-5", title: "Skardu Preparation", description: "Prepare and acclimatize." },
      { day: "Day 6", title: "Valley Drive", description: "Drive to Charakusa Valley." },
      { day: "Day 7-9", title: "Base Camp Trek", description: "Trek to Amin Braq Base Camp." },
      { day: "Day 10-16", title: "Rock Climbing", description: "Technical climbing and practice on various routes." },
      { day: "Day 17-19", title: "Peak Climbing", description: "Climb Amin Braq with multiple pitches." },
      { day: "Day 20", title: "Return", description: "Descent and return to Islamabad." },
    ],
    servicesIncluded: ["Permits", "Climbing guides", "Base camp", "All meals", "Equipment", "Ropes", "Communication"],
    servicesNotIncluded: ["International flights", "Personal gear", "Insurance", "Tips", "Personal spending"],
    requirements: ["Intermediate-advanced rock climbing", "5.8-5.9 climbing experience", "Alpine trekking background", "Technical skills"],
    highlights: ["Excellent rock climbing", "Pristine valleys", "Multiple route options", "Remote alpine climbing"],
  },
  {
    id: "nangma-valley",
    slug: "nangma-valley",
    name: "Nangma Valley Climbing",
    altitude: "5,200m",
    location: "Nangma Valley, Gilgit Baltistan, Pakistan",
    duration: "14-18 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - September",
    price: 16000,
    groupSize: "2-10 climbers",
    image: heroImage2,
    description: "Nangma Valley provides excellent rock climbing terrain with moderate technical difficulty and stunning mountain views.",
    overview: "The Nangma Valley Climbing expedition offers fantastic rock climbing in a beautiful alpine valley. Ideal for climbers building intermediate to advanced skills in a remote mountain environment.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Preparation", description: "Team briefing." },
      { day: "Day 3", title: "Skardu Flight", description: "Flight to Skardu." },
      { day: "Day 4-5", title: "Skardu Rest", description: "Acclimatization." },
      { day: "Day 6", title: "Valley Travel", description: "Travel to Nangma Valley." },
      { day: "Day 7-8", title: "Base Camp Setup", description: "Trek to and establish base camp." },
      { day: "Day 9-15", title: "Climbing Days", description: "Rock climbing on various routes." },
      { day: "Day 16-17", title: "Peak Climb", description: "Climb to valley summits." },
      { day: "Day 18", title: "Return", description: "Return to Islamabad." },
    ],
    servicesIncluded: ["Permits", "Climbing guides", "Base camp", "All meals", "Equipment", "Fixed ropes", "Communication"],
    servicesNotIncluded: ["International flights", "Personal gear", "Insurance", "Tips", "Personal spending"],
    requirements: ["Intermediate rock climbing experience", "5.7-5.8 climbing ability", "Alpine trekking experience", "Good fitness"],
    highlights: ["Beautiful valley climbing", "Moderate technical terrain", "Remote location", "Great training environment"],
  },
  {
    id: "latok-ogri",
    slug: "latok-ogri",
    name: "Latok Ogri Climbing",
    altitude: "5,840m",
    location: "Karakoram, Gilgit Baltistan, Pakistan",
    duration: "18-22 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - September",
    price: 21000,
    groupSize: "2-6 climbers",
    image: heroImage1,
    description: "Latok Ogri features challenging mixed climbing with technical rock and ice sections in a remote Karakoram setting.",
    overview: "The Latok Ogri Climbing expedition combines technical rock climbing with alpine ice climbing. A serious mountaineering objective for experienced climbers seeking remote alpine challenges.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Briefing", description: "Expedition orientation." },
      { day: "Day 3", title: "Skardu Flight", description: "Fly to Skardu." },
      { day: "Day 4-5", title: "Skardu Preparation", description: "Organize gear and logistics." },
      { day: "Day 6-7", title: "Askole Journey", description: "Travel to Askole." },
      { day: "Day 8-11", title: "Base Camp Trek", description: "Trek to Latok Base Camp." },
      { day: "Day 12-18", title: "Technical Climbing", description: "Mixed climbing on rock and ice." },
      { day: "Day 19-21", title: "Summit Push", description: "Climb Latok Ogri." },
      { day: "Day 22", title: "Return", description: "Descent and return." },
    ],
    servicesIncluded: ["Permits", "Expert guides", "Base camp", "All meals", "Climbing gear", "Ropes", "Communication equipment"],
    servicesNotIncluded: ["International flights", "Personal equipment", "Insurance", "Tips", "Personal expenses"],
    requirements: ["Advanced rock and ice climbing", "5.9+ experience", "Excellent alpine skills", "Remote climbing experience"],
    highlights: ["Mixed climbing adventure", "Technical challenges", "Remote Karakoram location", "Expert mountaineering"],
  },
  {
    id: "charakusa-valley",
    slug: "charakusa-valley",
    name: "Charakusa Valley Climbing",
    altitude: "5,100m",
    location: "Charakusa Valley, Gilgit Baltistan, Pakistan",
    duration: "14-18 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - September",
    price: 15500,
    groupSize: "2-10 climbers",
    image: heroImage2,
    description: "Charakusa Valley is renowned for its excellent rock climbing terrain with multiple crags and varied climbing routes.",
    overview: "The Charakusa Valley Climbing expedition offers world-class rock climbing in a pristine remote valley. Featuring multiple climbing areas with routes for various skill levels and stunning Karakoram scenery.",
    timeline: [
      { day: "Day 1-2", title: "Islamabad Preparation", description: "Team briefing." },
      { day: "Day 3", title: "Skardu Flight", description: "Flight to Skardu." },
      { day: "Day 4-5", title: "Skardu Rest", description: "Acclimatization." },
      { day: "Day 6", title: "Valley Drive", description: "Drive to Charakusa Valley." },
      { day: "Day 7-8", title: "Base Camp Trek", description: "Trek to valley base camp." },
      { day: "Day 9-15", title: "Multi-Day Climbing", description: "Rock climbing on various crags and routes." },
      { day: "Day 16-17", title: "Advanced Routes", description: "Climb challenging pitches." },
      { day: "Day 18", title: "Return", description: "Return to Islamabad." },
    ],
    servicesIncluded: ["Permits", "Climbing guides", "Base camp", "All meals", "Equipment", "Fixed ropes", "Safety gear"],
    servicesNotIncluded: ["International flights", "Personal climbing equipment", "Insurance", "Tips", "Personal costs"],
    requirements: ["Intermediate rock climbing skills", "5.7-5.8 climbing ability", "Alpine experience", "Good physical fitness"],
    highlights: ["Multiple crags", "Varied climbing routes", "Remote valley setting", "Excellent climbing conditions"],
  },
];

export function getExpeditionBySlug(slug: string): ExpeditionData | undefined {
  return expeditions.find((exp) => exp.slug === slug);
}

export function getExpeditionById(id: string): ExpeditionData | undefined {
  return expeditions.find((exp) => exp.id === id);
}
