import heroImage2 from "@assets/stock_images/majestic_mountain_pe_34e27685.jpg";
import heroImage1 from "@assets/stock_images/majestic_mountain_pe_743f6593.jpg";

[
  {
    id: "nanga-parbat-base-camp-trek",
    slug: "nanga-parbat-base-camp-trek",
    name: "Nanga Parbat Base Camp Trek",
    altitude: "4,100m",
    location: "Diamer District, Pakistan",
    duration: "10-12 Days",
    difficulty: "Difficult",
    bestSeason: "June - September",
    price: 1300,
    groupSize: "4-10 trekkers",
    image: heroImage2,
    description:
      "Trek to the base camp of Nanga Parbat, the 9th highest mountain in the world, via the scenic Diamir valley.",
    overview:
      "A challenging trek featuring dramatic mountain scenery and access to one of the world's most impressive peaks from the Diamir Face.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Travel to Chilas",
        description: "Journey from Islamabad",
      },
      {
        day: "Day 3-8",
        title: "Trek to Base Camp",
        description: "Trek through Diamir valley",
      },
      {
        day: "Day 9-12",
        title: "Exploration & Return",
        description: "Base camp views and return",
      },
    ],
    servicesIncluded: ["Permits", "Guides", "Meals", "Equipment", "Porters"],
    servicesNotIncluded: ["Flights", "Gear", "Insurance", "Tips"],
    requirements: ["Good fitness", "Trekking experience"],
    highlights: [
      "Nanga Parbat views",
      "Diamir valley",
      "High altitude scenery",
    ],
  },

  {
    id: "gasherbrum-iii",
    slug: "gasherbrum-iii-expedition",
    name: "Gasherbrum III Expedition",
    altitude: "7,952m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "40-45 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - August",
    price: 28000,
    groupSize: "4-8 climbers",
    image: heroImage1,
    description:
      "Gasherbrum III at 7,952m is the 15th highest mountain in the world. A challenging yet rewarding 7000m expedition.",
    overview:
      "The Gasherbrum III Expedition offers an excellent intermediate challenge between 6000m training peaks and 8000m summits. Located in the Karakoram, it provides spectacular alpine experiences with well-established climbing routes.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Arrival & Briefing",
        description:
          "Arrive in Islamabad for expedition briefing and final preparations.",
      },
      {
        day: "Day 3",
        title: "Fly to Skardu",
        description: "Scenic flight to Skardu with panoramic mountain views.",
      },
      {
        day: "Day 4-5",
        title: "Skardu Acclimatization",
        description:
          "Rest and acclimatization in Skardu with final gear checks.",
      },
      {
        day: "Day 6-7",
        title: "Drive to Askole",
        description: "Jeep journey to Askole and porter organization.",
      },
      {
        day: "Day 8-14",
        title: "Trek to Base Camp",
        description:
          "7-day trek through Baltoro Glacier to Gasherbrum Base Camp.",
      },
      {
        day: "Day 15-20",
        title: "Base Camp Setup",
        description: "Establish base camp and acclimatization hikes.",
      },
      {
        day: "Day 21-35",
        title: "Camp Rotations",
        description:
          "Establish higher camps with progressive acclimatization climbs.",
      },
      {
        day: "Day 36-42",
        title: "Summit Window",
        description: "Wait for optimal weather and summit push.",
      },
      {
        day: "Day 43-45",
        title: "Descent & Return",
        description: "Descend and trek back to Askole, return to Islamabad.",
      },
    ],
    servicesIncluded: [
      "Climbing permits",
      "Liaison Officer",
      "Professional guides",
      "All meals",
      "Camping equipment",
      "Fixed ropes",
      "Emergency communication",
      "Porter services",
      "Ground transportation",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal climbing gear",
      "Travel insurance",
      "Staff tips",
      "Personal expenses",
    ],
    requirements: [
      "Previous 6000m+ experience",
      "Technical climbing skills",
      "Excellent physical fitness",
      "Medical clearance",
    ],
    highlights: [
      "Climb a technical 7000m peak",
      "Experience Baltoro Glacier",
      "Alpine climbing adventure",
      "Spectacular Karakoram views",
    ],
  },

  {
    id: "k6",
    slug: "k6-expedition",
    name: "K6 Expedition",
    altitude: "7,462m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "30-35 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - August",
    price: 23000,
    groupSize: "4-10 climbers",
    image: heroImage1,
    description:
      "K6 at 7,462m is one of the most accessible 7000m peaks in the Karakoram, ideal for ambitious high-altitude mountaineers.",
    overview:
      "The K6 Expedition is perfect for climbers seeking their first 7000m summit or those training for higher peaks. The mountain offers moderate technical difficulty with good climbing routes and high success rates.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Islamabad Arrival",
        description: "Team briefing and preparation.",
      },
      {
        day: "Day 3",
        title: "Skardu Flight",
        description: "Flight to Skardu.",
      },
      {
        day: "Day 4-5",
        title: "Skardu Acclimatization",
        description: "Rest and acclimatization in Skardu.",
      },
      {
        day: "Day 6-7",
        title: "Askole Drive",
        description: "Jeep to Askole and porter setup.",
      },
      {
        day: "Day 8-11",
        title: "Base Camp Trek",
        description: "Trek to K6 Base Camp.",
      },
      {
        day: "Day 12-17",
        title: "Base Camp Rest",
        description: "Establish camp and acclimatize.",
      },
      {
        day: "Day 18-28",
        title: "Camp Climbs",
        description: "Establish camps with multiple rotations.",
      },
      {
        day: "Day 29-33",
        title: "Summit & Descent",
        description: "Summit push and descent.",
      },
      {
        day: "Day 34-35",
        title: "Return Journey",
        description: "Return to Islamabad.",
      },
    ],
    servicesIncluded: [
      "Permits",
      "Liaison Officer",
      "Professional guides",
      "All meals",
      "Equipment",
      "Fixed ropes",
      "Communication",
      "Porters",
      "Transportation",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal gear",
      "Insurance",
      "Tips",
      "Personal spending",
    ],
    requirements: [
      "5000m+ climbing experience",
      "Basic technical skills",
      "Good physical fitness",
      "Medical approval",
    ],
    highlights: [
      "Accessible 7000m peak",
      "Perfect first 7000m mountain",
      "Great views",
      "Good success rates",
    ],
  },

  {
    id: "pastore-peak",
    slug: "pastore-peak-expedition",
    name: "Pastore Peak Expedition",
    altitude: "6,618m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "28-32 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - August",
    price: 20000,
    groupSize: "4-8 climbers",
    image: heroImage2,
    description:
      "Pastore Peak at 6,618m combines mountaineering with technical climbing for an intermediate mountain experience.",
    overview:
      "The Pastore Peak Expedition offers an excellent stepping stone for climbers progressing toward 7000m peaks. The mountain features moderate technical climbing with panoramic views of the Karakoram and Hindu Kush ranges.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Islamabad Arrival",
        description: "Team briefing and expedition orientation.",
      },
      {
        day: "Day 3",
        title: "Skardu Flight",
        description: "Flight to Skardu with mountain views.",
      },
      {
        day: "Day 4-5",
        title: "Skardu Rest",
        description: "Acclimatization and preparation.",
      },
      {
        day: "Day 6-7",
        title: "Askole Drive",
        description: "Travel to Askole and porter setup.",
      },
      {
        day: "Day 8-12",
        title: "Base Camp Trek",
        description: "Trek to Pastore Peak Base Camp.",
      },
      {
        day: "Day 13-18",
        title: "Base Camp Acclimatization",
        description: "Establish camp and acclimatization hikes.",
      },
      {
        day: "Day 19-28",
        title: "Higher Camp Climbs",
        description: "Establish camps with multiple rotations.",
      },
      {
        day: "Day 29-31",
        title: "Summit Push",
        description: "Summit attempt during weather window.",
      },
      {
        day: "Day 32",
        title: "Return",
        description: "Descent and return to Islamabad.",
      },
    ],
    servicesIncluded: [
      "Permits and royalties",
      "Liaison Officer",
      "Expert guides",
      "All meals",
      "High-altitude equipment",
      "Fixed ropes",
      "Communication",
      "Porters",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal gear",
      "Insurance",
      "Staff tips",
      "Personal costs",
    ],
    requirements: [
      "5000m+ climbing experience",
      "Solid technical climbing skills",
      "Good physical fitness",
      "Medical clearance",
    ],
    highlights: [
      "Technical 6000m climb",
      "Great training mountain",
      "Panoramic views",
      "Karakoram adventure",
    ],
  },
  {
    id: "khusrogang",
    slug: "khusrogang-expedition",
    name: "Khusrogang Expedition",
    altitude: "6,400m",
    location: "Gilgit Baltistan, Pakistan",
    duration: "26-30 Days",
    difficulty: "Moderate",
    bestSeason: "June - August",
    price: 19000,
    groupSize: "4-10 climbers",
    image: heroImage1,
    description:
      "Khusrogang at 6,400m provides an excellent training ground for higher altitude climbing with moderate technical difficulty.",
    overview:
      "The Khusrogang Expedition is perfect for mountaineers building experience toward 7000m peaks. The mountain offers accessible climbing routes with good acclimatization opportunities and spectacular mountain scenery.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Islamabad Briefing",
        description: "Team gathering and final briefings.",
      },
      {
        day: "Day 3",
        title: "Skardu Flight",
        description: "Flight to Skardu.",
      },
      {
        day: "Day 4-5",
        title: "Skardu Acclimatization",
        description: "Rest and acclimatization in Skardu.",
      },
      {
        day: "Day 6-7",
        title: "Askole Journey",
        description: "Drive to Askole and organize logistics.",
      },
      {
        day: "Day 8-11",
        title: "Base Camp Trek",
        description: "Trek to Khusrogang Base Camp.",
      },
      {
        day: "Day 12-17",
        title: "Base Camp Setup",
        description: "Establish camp and acclimatization activities.",
      },
      {
        day: "Day 18-26",
        title: "Camp Establishment",
        description: "Set up higher camps with climbing rotations.",
      },
      {
        day: "Day 27-29",
        title: "Summit Window",
        description: "Summit attempt during favorable weather.",
      },
      {
        day: "Day 30",
        title: "Descent",
        description: "Descend and return to Islamabad.",
      },
    ],
    servicesIncluded: [
      "Climbing permits",
      "Liaison Officer",
      "Experienced guides",
      "All meals",
      "Camping equipment",
      "Fixed ropes",
      "Radio communication",
      "Porter services",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal climbing equipment",
      "Insurance",
      "Staff gratuities",
      "Personal spending",
    ],
    requirements: [
      "Previous 5000m+ experience",
      "Intermediate technical skills",
      "Strong physical fitness",
      "Medical approval",
    ],
    highlights: [
      "Moderate 6000m peak",
      "Good training mountain",
      "Accessible climbing",
      "Alpine mountain views",
    ],
  },
  {
    id: "trango-tower",
    slug: "trango-tower",
    name: "Trango Tower Climbing",
    altitude: "6,286m",
    location: "Karakoram, Gilgit Baltistan, Pakistan",
    duration: "20-25 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - September",
    price: 22000,
    groupSize: "2-6 climbers",
    image: heroImage1,
    description:
      "Trango Tower is one of the most challenging and iconic rock climbing destinations in the world, featuring pristine granite walls.",
    overview:
      "The Trango Tower Climbing expedition offers world-class rock climbing on one of the most magnificent granite towers. This advanced technical climb requires serious mountaineering and rock climbing expertise.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Islamabad Briefing",
        description: "Team gathering and expedition preparation.",
      },
      { day: "Day 3", title: "Skardu Flight", description: "Fly to Skardu." },
      {
        day: "Day 4-5",
        title: "Skardu Preparation",
        description: "Organize equipment and logistics.",
      },
      {
        day: "Day 6-7",
        title: "Askole Journey",
        description: "Travel to Askole base village.",
      },
      {
        day: "Day 8-11",
        title: "Trek to Base Camp",
        description: "Trek to Trango Base Camp via Baltoro Glacier.",
      },
      {
        day: "Day 12-20",
        title: "Climbing & Acclimatization",
        description: "Rock climbing and technical training on various pitches.",
      },
      {
        day: "Day 21-24",
        title: "Tower Attempt",
        description: "Climb Trango Tower with multiple advanced pitches.",
      },
      {
        day: "Day 25",
        title: "Return",
        description: "Descent and return to Islamabad.",
      },
    ],
    servicesIncluded: [
      "Permits",
      "Expert climbing guides",
      "Base camp equipment",
      "All meals",
      "Fixed ropes",
      "Communication gear",
      "Porter services",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal climbing gear",
      "Insurance",
      "Staff tips",
      "Personal expenses",
    ],
    requirements: [
      "Advanced rock climbing experience",
      "Previous 5.10+ climbing background",
      "Excellent physical fitness",
      "Technical mountaineering skills",
    ],
    highlights: [
      "Iconic granite tower",
      "World-class climbing",
      "Advanced technical routes",
      "Alpine adventure",
    ],
  },
  {
    id: "great-tower",
    slug: "great-tower",
    name: "Great Tower Climbing",
    altitude: "5,971m",
    location: "Karakoram, Gilgit Baltistan, Pakistan",
    duration: "18-22 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - September",
    price: 20000,
    groupSize: "2-6 climbers",
    image: heroImage2,
    description:
      "Great Tower offers challenging rock climbing with stunning Karakoram views and technical alpine routes.",
    overview:
      "The Great Tower Climbing expedition combines technical rock climbing with alpine mountaineering. A fantastic objective for climbers seeking to develop advanced skills in high-altitude rock climbing.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Islamabad Arrival",
        description: "Team briefing and preparations.",
      },
      {
        day: "Day 3",
        title: "Skardu Flight",
        description: "Flight to Skardu.",
      },
      {
        day: "Day 4-5",
        title: "Skardu Rest",
        description: "Acclimatization and gear organization.",
      },
      {
        day: "Day 6-7",
        title: "Askole Drive",
        description: "Travel to Askole.",
      },
      {
        day: "Day 8-10",
        title: "Base Camp Trek",
        description: "Trek to Great Tower Base Camp.",
      },
      {
        day: "Day 11-18",
        title: "Climbing Days",
        description: "Technical climbing on various rock pitches.",
      },
      {
        day: "Day 19-21",
        title: "Tower Climb",
        description: "Summit attempt on Great Tower.",
      },
      {
        day: "Day 22",
        title: "Return",
        description: "Descent and return journey.",
      },
    ],
    servicesIncluded: [
      "Permits",
      "Rock climbing guides",
      "Base camp setup",
      "All meals",
      "Climbing equipment",
      "Communication",
      "Porters",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal climbing gear",
      "Insurance",
      "Tips",
      "Personal costs",
    ],
    requirements: [
      "Advanced rock climbing skills",
      "5.9-5.10 climbing experience",
      "Alpine mountaineering experience",
      "Technical ability",
    ],
    highlights: [
      "Excellent rock climbing",
      "Alpine environment",
      "Advanced technical routes",
      "Karakoram wilderness",
    ],
  },
  {
    id: "amin-braq",
    slug: "amin-braq",
    name: "Amin Braq Climbing",
    altitude: "5,610m",
    location: "Charakusa Valley, Gilgit Baltistan, Pakistan",
    duration: "16-20 Days",
    difficulty: "Difficult",
    bestSeason: "June - September",
    price: 18000,
    groupSize: "2-8 climbers",
    image: heroImage1,
    description:
      "Amin Braq in the Charakusa Valley offers excellent rock climbing with multiple route options and stunning alpine scenery.",
    overview:
      "The Amin Braq Climbing expedition provides superb rock climbing in a pristine alpine environment. Perfect for climbers developing technical skills with several challenging pitches and beautiful Karakoram views.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Islamabad Briefing",
        description: "Team orientation.",
      },
      { day: "Day 3", title: "Skardu Flight", description: "Fly to Skardu." },
      {
        day: "Day 4-5",
        title: "Skardu Preparation",
        description: "Prepare and acclimatize.",
      },
      {
        day: "Day 6",
        title: "Valley Drive",
        description: "Drive to Charakusa Valley.",
      },
      {
        day: "Day 7-9",
        title: "Base Camp Trek",
        description: "Trek to Amin Braq Base Camp.",
      },
      {
        day: "Day 10-16",
        title: "Rock Climbing",
        description: "Technical climbing and practice on various routes.",
      },
      {
        day: "Day 17-19",
        title: "Peak Climbing",
        description: "Climb Amin Braq with multiple pitches.",
      },
      {
        day: "Day 20",
        title: "Return",
        description: "Descent and return to Islamabad.",
      },
    ],
    servicesIncluded: [
      "Permits",
      "Climbing guides",
      "Base camp",
      "All meals",
      "Equipment",
      "Ropes",
      "Communication",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal gear",
      "Insurance",
      "Tips",
      "Personal spending",
    ],
    requirements: [
      "Intermediate-advanced rock climbing",
      "5.8-5.9 climbing experience",
      "Alpine trekking background",
      "Technical skills",
    ],
    highlights: [
      "Excellent rock climbing",
      "Pristine valleys",
      "Multiple route options",
      "Remote alpine climbing",
    ],
  },
  {
    id: "nangma-valley",
    slug: "nangma-valley",
    name: "Nangma Valley Climbing",
    altitude: "5,200m",
    location: "Nangma Valley, Gilgit Baltistan, Pakistan",
    duration: "14-18 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - September",
    price: 16000,
    groupSize: "2-10 climbers",
    image: heroImage2,
    description:
      "Nangma Valley provides excellent rock climbing terrain with moderate technical difficulty and stunning mountain views.",
    overview:
      "The Nangma Valley Climbing expedition offers fantastic rock climbing in a beautiful alpine valley. Ideal for climbers building intermediate to advanced skills in a remote mountain environment.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Islamabad Preparation",
        description: "Team briefing.",
      },
      {
        day: "Day 3",
        title: "Skardu Flight",
        description: "Flight to Skardu.",
      },
      { day: "Day 4-5", title: "Skardu Rest", description: "Acclimatization." },
      {
        day: "Day 6",
        title: "Valley Travel",
        description: "Travel to Nangma Valley.",
      },
      {
        day: "Day 7-8",
        title: "Base Camp Setup",
        description: "Trek to and establish base camp.",
      },
      {
        day: "Day 9-15",
        title: "Climbing Days",
        description: "Rock climbing on various routes.",
      },
      {
        day: "Day 16-17",
        title: "Peak Climb",
        description: "Climb to valley summits.",
      },
      { day: "Day 18", title: "Return", description: "Return to Islamabad." },
    ],
    servicesIncluded: [
      "Permits",
      "Climbing guides",
      "Base camp",
      "All meals",
      "Equipment",
      "Fixed ropes",
      "Communication",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal gear",
      "Insurance",
      "Tips",
      "Personal spending",
    ],
    requirements: [
      "Intermediate rock climbing experience",
      "5.7-5.8 climbing ability",
      "Alpine trekking experience",
      "Good fitness",
    ],
    highlights: [
      "Beautiful valley climbing",
      "Moderate technical terrain",
      "Remote location",
      "Great training environment",
    ],
  },
  {
    id: "latok-ogri",
    slug: "latok-ogri",
    name: "Latok Ogri Climbing",
    altitude: "5,840m",
    location: "Karakoram, Gilgit Baltistan, Pakistan",
    duration: "18-22 Days",
    difficulty: "Very Difficult",
    bestSeason: "June - September",
    price: 21000,
    groupSize: "2-6 climbers",
    image: heroImage1,
    description:
      "Latok Ogri features challenging mixed climbing with technical rock and ice sections in a remote Karakoram setting.",
    overview:
      "The Latok Ogri Climbing expedition combines technical rock climbing with alpine ice climbing. A serious mountaineering objective for experienced climbers seeking remote alpine challenges.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Islamabad Briefing",
        description: "Expedition orientation.",
      },
      { day: "Day 3", title: "Skardu Flight", description: "Fly to Skardu." },
      {
        day: "Day 4-5",
        title: "Skardu Preparation",
        description: "Organize gear and logistics.",
      },
      {
        day: "Day 6-7",
        title: "Askole Journey",
        description: "Travel to Askole.",
      },
      {
        day: "Day 8-11",
        title: "Base Camp Trek",
        description: "Trek to Latok Base Camp.",
      },
      {
        day: "Day 12-18",
        title: "Technical Climbing",
        description: "Mixed climbing on rock and ice.",
      },
      {
        day: "Day 19-21",
        title: "Summit Push",
        description: "Climb Latok Ogri.",
      },
      { day: "Day 22", title: "Return", description: "Descent and return." },
    ],
    servicesIncluded: [
      "Permits",
      "Expert guides",
      "Base camp",
      "All meals",
      "Climbing gear",
      "Ropes",
      "Communication equipment",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal equipment",
      "Insurance",
      "Tips",
      "Personal expenses",
    ],
    requirements: [
      "Advanced rock and ice climbing",
      "5.9+ experience",
      "Excellent alpine skills",
      "Remote climbing experience",
    ],
    highlights: [
      "Mixed climbing adventure",
      "Technical challenges",
      "Remote Karakoram location",
      "Expert mountaineering",
    ],
  },
  {
    id: "charakusa-valley",
    slug: "charakusa-valley",
    name: "Charakusa Valley Climbing",
    altitude: "5,100m",
    location: "Charakusa Valley, Gilgit Baltistan, Pakistan",
    duration: "14-18 Days",
    difficulty: "Moderate to Difficult",
    bestSeason: "June - September",
    price: 15500,
    groupSize: "2-10 climbers",
    image: heroImage2,
    description:
      "Charakusa Valley is renowned for its excellent rock climbing terrain with multiple crags and varied climbing routes.",
    overview:
      "The Charakusa Valley Climbing expedition offers world-class rock climbing in a pristine remote valley. Featuring multiple climbing areas with routes for various skill levels and stunning Karakoram scenery.",
    timeline: [
      {
        day: "Day 1-2",
        title: "Islamabad Preparation",
        description: "Team briefing.",
      },
      {
        day: "Day 3",
        title: "Skardu Flight",
        description: "Flight to Skardu.",
      },
      { day: "Day 4-5", title: "Skardu Rest", description: "Acclimatization." },
      {
        day: "Day 6",
        title: "Valley Drive",
        description: "Drive to Charakusa Valley.",
      },
      {
        day: "Day 7-8",
        title: "Base Camp Trek",
        description: "Trek to valley base camp.",
      },
      {
        day: "Day 9-15",
        title: "Multi-Day Climbing",
        description: "Rock climbing on various crags and routes.",
      },
      {
        day: "Day 16-17",
        title: "Advanced Routes",
        description: "Climb challenging pitches.",
      },
      { day: "Day 18", title: "Return", description: "Return to Islamabad." },
    ],
    servicesIncluded: [
      "Permits",
      "Climbing guides",
      "Base camp",
      "All meals",
      "Equipment",
      "Fixed ropes",
      "Safety gear",
    ],
    servicesNotIncluded: [
      "International flights",
      "Personal climbing equipment",
      "Insurance",
      "Tips",
      "Personal costs",
    ],
    requirements: [
      "Intermediate rock climbing skills",
      "5.7-5.8 climbing ability",
      "Alpine experience",
      "Good physical fitness",
    ],
    highlights: [
      "Multiple crags",
      "Varied climbing routes",
      "Remote valley setting",
      "Excellent climbing conditions",
    ],
  },
];
