import type { VercelRequest, VercelResponse } from '@vercel/node';

const sampleTripsData = [
  {
    id: "1",
    title: "K2 Expedition",
    description: "K2 or Chogori, the world's second highest peak at 8611m, is located in the Karakoram Range. This expedition offers the ultimate mountaineering challenge with professional guides and comprehensive support throughout your journey to the summit.",
    shortDescription: "K2 or Chogori world second highest peak 8611m located in Karakoram Range...",
    destination: "Gilgit Baltistan",
    duration: "60 Days",
    price: 12500,
    category: "Expedition",
    season: "Summer",
    imageUrl: "https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800&q=80",
    rating: 5,
    featured: true,
    difficulty: "Extreme",
    maxGroupSize: 12,
  },
  {
    id: "2",
    title: "Nanga Parbat Expedition",
    description: "Nanga Parbat 8126m is the ninth highest mountain in the world and known as the 'Killer Mountain'. This expedition takes you through the Diamir Face with experienced guides.",
    shortDescription: "Nanga Parbat 8126m is the ninth highest mountain in the world and...",
    destination: "Diamer District",
    duration: "50 Days - 49 Nights",
    price: 11900,
    category: "Expedition",
    season: "Summer",
    imageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80",
    rating: 5,
    featured: true,
    difficulty: "Extreme",
    maxGroupSize: 10,
  },
  {
    id: "3",
    title: "Broad Peak Expedition",
    description: "Broad Peak 8047m situated in the Karakoram Range in Pakistan. Join our experienced team for this challenging yet rewarding 8000m expedition.",
    shortDescription: "Broad Peak 8047m situated Karakoram Range in Pakistan on...",
    destination: "Gilgit Baltistan",
    duration: "45 Days",
    price: 9800,
    category: "Expedition",
    season: "Summer",
    imageUrl: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800&q=80",
    rating: 5,
    featured: true,
    difficulty: "Extreme",
    maxGroupSize: 12,
  },
  {
    id: "5",
    title: "Skardu Valley Blossom Tour",
    description: "North Karakoram offers the most beautiful city Skardu with cherry blossoms in spring. Experience the magical pink valley with comfortable accommodations.",
    shortDescription: "North Karakoram offering the most beautiful city Skardu and...",
    destination: "Skardu",
    duration: "10 Days - 9 Nights",
    price: 1650,
    category: "Tour",
    season: "Spring",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    rating: 5,
    featured: true,
    difficulty: "Easy",
    maxGroupSize: 20,
  },
  {
    id: "10",
    title: "Concordia Trek",
    description: "Trek to the throne room of the mountain gods - Concordia, surrounded by four 8000m peaks including K2, Broad Peak, and the Gasherbrums.",
    shortDescription: "Trek to Concordia, surrounded by four 8000m peaks including K2...",
    destination: "Gilgit Baltistan",
    duration: "21 Days - 20 Nights",
    price: 3200,
    category: "Trekking",
    season: "Summer",
    imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
    rating: 5,
    featured: true,
    difficulty: "Advanced",
    maxGroupSize: 14,
  },
];

export default function handler(req: VercelRequest, res: VercelResponse) {
  return res.status(200).json(sampleTripsData);
}
